from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from io import BytesIO
from datetime import datetime
import textwrap

from database import get_db
from models import User, Prediction
from auth import get_current_user

router = APIRouter(prefix="/report", tags=["report"])


def generate_pdf_report(user: User, prediction: Prediction) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()

    teal = colors.HexColor("#0d9488")
    dark = colors.HexColor("#1e293b")
    light_gray = colors.HexColor("#f1f5f9")

    title_style = ParagraphStyle(
        "Title", parent=styles["Title"], textColor=teal, fontSize=22, spaceAfter=6
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"], textColor=dark, fontSize=13, spaceAfter=4
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=10, spaceAfter=4, leading=14
    )
    sub_style = ParagraphStyle(
        "Sub", parent=styles["Normal"], fontSize=9, textColor=colors.gray
    )

    story = []

    # Header
    story.append(Paragraph("🏥 CuraAI", title_style))
    story.append(Paragraph("Comprehensive AI Health Assessment Report", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=teal, spaceAfter=12))

    # User Info
    story.append(Paragraph("Patient Information", heading_style))
    user_data = [
        ["Name", user.name],
        ["Email", user.email],
        ["Prediction ID", prediction.id[:8]],
        ["Generated By", "CuraAI v1.0"],
        ["Report Date", datetime.utcnow().strftime("%B %d, %Y %H:%M UTC")],
    ]
    t = Table(user_data, colWidths=[4 * cm, 12 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), light_gray),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5 * cm))

    # Symptoms
    story.append(Paragraph("Reported Symptoms", heading_style))
    for symptom in prediction.symptoms:
        story.append(
            Paragraph(
                f"• {symptom.title()}",
                body_style
            )
        )
    story.append(Spacer(1, 0.3 * cm))

    # Diagnosis
    story.append(Paragraph("Diagnosis Result", heading_style))
    diag_data = [
        ["Predicted Disease", prediction.disease],
        ["Confidence Score", f"{prediction.confidence:.1f}%"],
        ["Risk Level", prediction.risk_level or "N/A"],
        ["Severity Score", str(prediction.severity_score or "N/A")],
        ["Health Score", f"{prediction.health_score:.1f}/100" if prediction.health_score else "N/A"],
    ]
    story.append(Spacer(1, 0.3 * cm))

    story.append(
        Paragraph(
            f"<b>{prediction.disease}</b>",
            ParagraphStyle(
                "DiseaseTitle",
                parent=styles["Title"],
                fontSize=24,
                textColor=teal,
                alignment=1
            )
        )
    )

    story.append(
        Paragraph(
            f"Confidence: {prediction.confidence:.1f}% | Risk: {prediction.risk_level}",
            ParagraphStyle(
                "DiseaseSub",
                parent=styles["Normal"],
                alignment=1,
                textColor=colors.grey
            )
        )
    )

    story.append(Spacer(1, 0.4 * cm))

    t2 = Table(diag_data, colWidths=[5 * cm, 11 * cm])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), light_gray),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t2)
    story.append(Spacer(1, 0.5 * cm))
    risk_color = {
        "Low": "#16a34a",
        "Moderate": "#f59e0b",
        "High": "#ea580c",
        "Critical": "#dc2626"
    }.get(prediction.risk_level, "#64748b")

    story.append(
        Paragraph(
            f"""
            <font color="{risk_color}">
            <b>Risk Assessment: {prediction.risk_level}</b>
            </font>
            """,
            body_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Health Score:</b> {prediction.health_score}/100",
            heading_style
        )
    )

    # Description
    if prediction.description:
        story.append(Paragraph("Disease Description", heading_style))
        story.append(Paragraph(prediction.description, body_style))
        story.append(Spacer(1, 0.3 * cm))

    def bullet_section(title, items):
        if items:
            story.append(Paragraph(title, heading_style))
            for item in items:
                story.append(Paragraph(f"• {item}", body_style))
            story.append(Spacer(1, 0.3 * cm))

    bullet_section("Recommended Medications", prediction.medications or [])
    bullet_section("Recommended Diet", prediction.diet or [])
    bullet_section("Precautions", prediction.precautions or [])
    bullet_section("Workout / Exercise Suggestions", prediction.workout or [])

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceAfter=6))
    story.append(
        Paragraph(
            """
            <b>Medical Disclaimer</b><br/>
            This report has been generated using AI models and
            symptom-based analysis. It is intended solely for educational
            and informational purposes and should not replace professional
            medical advice, diagnosis, or treatment.
            """,
            sub_style
        )
    )

    doc.build(story)

    story.append(
    Paragraph(
        "Generated securely by CuraAI • AI Healthcare Intelligence Platform",
        ParagraphStyle(
            "Footer",
            parent=sub_style,
            alignment=1
        )
    )
)
    return buffer.getvalue()

    
    


@router.get("/{prediction_id}")
def download_report(
    prediction_id: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    prediction = db.query(Prediction).filter(
        Prediction.id == prediction_id,
        Prediction.user_id == current_user.id,
    ).first()
    if not prediction:
        raise HTTPException(status_code=404, detail="Prediction not found")

    pdf_bytes = generate_pdf_report(current_user, prediction)
    filename = f"health_report_{prediction.disease.replace(' ', '_')}_{prediction_id[:8]}.pdf"

    return StreamingResponse(
        BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )

    